name: CI Pipeline

on:
  pull_request:
    branches: [develop, main] # feature -> develop, develop -> main 으로 PR이 생기면 이벤트 발생
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

        # 빌드 및 테스트
      - name: Build with Gradle
        run: ./gradlew clean build
